namespace:
  name: default

gateway:
  name: istio-ingress-gateway


VirtualService:
    hosts: web.aj.com
       

     


service:
  active: active-service
  preview: preview-service
  labels:
    app: openai-app

rollout:
  name: rollout-bluegreen
  labels:
    app: openai-app
  # progressdeadlineseconds: 600
  replicas: 3
  revisionhistorylimit: 2
  containers:
    name: openai-app-container
    image: ajmaldocker07/openai-node
    tag: 25

