apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs
spec:
  hosts:
  - {{ .Values.VirtualService.hosts }}
  gateways:
  - {{ .Values.gateway.name }}
  http:
  - match:
    - uri:
        prefix: /kiali
    route:
      - destination:
          host: kiali.istio-system.svc.cluster.local
          port:
            number: 20001
  - route:
    - destination:
        host: active-service.default.svc.cluster.local
        port:
          number: 5000
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-preview
spec:
  hosts:
  - web.preview.com
  gateways:
  - istio-ingress-gateway
  http:
    - route:
       - destination:
           host: preview-service.default.svc.cluster.local
           port:
              number: 5000
