apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.active }}
spec:
  selector:
    app: {{ .Values.service.labels.app }}
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer